### PR TITLE
Better handling of optional arguments

### LINKED ISSUE #7: improve test cov

### LINKED ISSUE #8: docstring format is incorrect
https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L8

### LINKED ISSUE #9: create_qobj -> convert_to_qobj
let's be consistent with other packages

https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L23

### LINKED ISSUE #10: don't write python for optional arguments...
https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L44

this is not how you write optional arguments in Julia, let's use a kwargs instead, and annotate the kwargs as `Bool`

### LINKED ISSUE #11: use UUID not randstring
https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L23

### LINKED ISSUE #12: use the kwargs syntax sugar
https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L26

just write

```julia
Qobj(;qobj_id = id, type = "QASM", schema_version = v"1", header, experiments, config)
```

### PR DESCRIPTION
**Pull request by Sov-trotter**
closes #10, #12 & #11

>we can have a Qobj specific block here (say Experiment{N} <: AbstractBlock{N}), that takes a ChainBlock and a config and header, then accept a list of them and lower them to Qobj.

This wasn't needed since multiple dispatch made things easier.

Also I had to use `@options` from IBMQClient to get around this [error](https://github.com/JuliaLang/julia/issues/10146)

### CODE REVIEW

File: src/qobj.jl [hunk 1]
```diff
@@ -1,7 +1,15 @@
 using Random
 
+IBMQClient.@option struct ExpOptions
```
Comment (Roger-luo) [inline src/qobj.jl]: please using `Configurations` directly instead calling it from IBMQClient

File: src/qobj.jl [hunk 2]
```diff
@@ -1,7 +1,15 @@
...
+    id::String
+    header::IBMQClient.Maybe{Dict} = nothing
+    nshots::Int = 1024
+    exp_header::IBMQClient.Maybe{Vector} = nothing
```
Comment (Roger-luo) [inline src/qobj.jl]: `Maybe` is also exported from `Configurations`

Comment (Roger-luo) [inline src/qobj.jl]:
```suggestion
    exp_header::IBMQClient.Maybe{Vector{Any}} = nothing
```

**Review by Roger-luo — CHANGES_REQUESTED** [review]
FYI. that should be an error at least before 2.0, you must use things `Configurations` to have the keyword struct syntax. And for web applications, it is usually to use things like `Configurations` to define a schema for security reason.

File: src/qobj.jl (hunk 2 above)
Comment (Sov-trotter) [reply src/qobj.jl]: We can have it as a `Dict` IMO.

Comment (Roger-luo) [reply src/qobj.jl]: either `Dict` or `Any`, but should put a type there.

Comment (Roger-luo) [reply src/qobj.jl]: if you put a `Dict`, remember to fill the parameters as `Dict{String, Any}`

File: src/qobj.jl [hunk 3]
```diff
@@ -1,7 +1,7 @@
-using Random
+using UUIDs
 
 IBMQClient.@option struct ExpOptions
-    id::String
+    id::String = uuid1()
```
Comment (Roger-luo) [inline src/qobj.jl]: I think you need to do a conversion here from `UUID` to `String`

File: src/qobj.jl [hunk 4]
```diff
@@ -1,7 +1,7 @@
...
     header::IBMQClient.Maybe{Dict} = nothing
```
Comment (Roger-luo) [inline src/qobj.jl]: this is the same, write the actual type instead of just `Dict`

File: src/qobj.jl [hunk 5]
```diff
@@ -41,33 +52,12 @@ end
...
-    return experiments
-end
+create_experiment(qc::Vector{<:AbstractBlock{N}}, exp_header::Nothing, exp_config::Nothing) where N = collect(create_experiment!(qc[i], nothing, nothing) for i in 1:length(qc))
+create_experiment(qc::Vector{<:AbstractBlock{N}}, exp_header::Array, exp_config::Array) where N =  collect(create_experiment!(qc[i], exp_header[i], exp_config[i]) for i in 1:length(qc))
+create_experiment(qc::Vector{<:AbstractBlock{N}}, exp_header::Nothing, exp_config::Array) where N = collect(create_experiment!(qc[i], nothing, exp_config[i]) for i in 1:length(qc))
+create_experiment(qc::Vector{<:AbstractBlock{N}}, exp_header::Array, exp_config::Nothing) where N = collect(create_experiment!(qc[i], exp_header[i], nothing) for i in 1:length(qc))
 
-function create_experiment!(qc::AbstractBlock{N}, exp_header = nothing, exp_config = nothing) where N
+function create_experiment!(qc::AbstractBlock{N}, exp_header, exp_config) where N
     exp_inst = generate_inst(qc)
```
Comment (Roger-luo) [inline src/qobj.jl:86]: why `create_experiment!` has a `!` here? it doesn't modify the first arugment

**Comment by Roger-luo** [comment]
also please remember to format the doc strings. For this part you have to do it manually, run JuliaFormatter in this PR before we merge things would also be a good idea.

File: test/qobjtoqbir.jl [hunk 6]
```diff
@@ -71,22 +78,29 @@ YaoBlocks.@dumpload_fallback U2 U2
...
-        while name[nc+1] == 'c' && nc<length(name)
-            nc += 1
-        end
-        if nc > 0
-            control(n, locs[1:nc], locs[nc+1:end]=>name_index(name[nc+1:end], x.params))
-        else
-            put(n, locs=>name_index(name, x.params))
-        end
-    end)
+    n = maximum(x -> maximum(x.qubits), inst) + 1
```
Comment (Roger-luo) [inline test/qobjtoqbir.jl]: we don't actually need to convert Qobj back to QBIR, since Qobj is for IBMQ client, but since you have done it, let's just include this too!

File: src/qobj.jl [hunk 7]
```diff
@@ -1,86 +1,102 @@
-using Random
+using Configurations, UUIDs
+
+@option struct ExpOptions
+    id::String = "$(uuid1())"
```
Comment (Roger-luo) [inline src/qobj.jl]:
```suggestion
    id::String = string(uuid1())
```

**Comment by Roger-luo** [comment]
let's have some more tests to push the covarage above 80% at least.

**Comment by Roger-luo** [comment]
nice work! thanks
